/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyktx;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author tuanta
 */
public class KTXManagement extends javax.swing.JFrame {

    /**
     * Creates new form KTXManagement
     */
    public KTXManagement() {
        initComponents();
        setLocationRelativeTo(null);
        setColor_317(TrangChu_317); 
        bd_tc_317.setOpaque(true);
     resetColor_317(new JPanel[]{CaiDat_317,DangXuat_317}, new JPanel[]{bd_cd_317, bd_dx_317});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_317 = new javax.swing.JPanel();
        sideBar_317 = new javax.swing.JPanel();
        CaiDat_317 = new javax.swing.JPanel();
        icon_cd_317 = new javax.swing.JLabel();
        bd_cd_317 = new javax.swing.JPanel();
        Name_cd_317 = new javax.swing.JLabel();
        TrangChu_317 = new javax.swing.JPanel();
        icon_TC_317 = new javax.swing.JLabel();
        bd_tc_317 = new javax.swing.JPanel();
        Name_TC_317 = new javax.swing.JLabel();
        DangXuat_317 = new javax.swing.JPanel();
        icon_dx_317 = new javax.swing.JLabel();
        bd_dx_317 = new javax.swing.JPanel();
        Name_dx_317 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Name_KTX_317 = new javax.swing.JLabel();
        header_317 = new javax.swing.JPanel();
        close_317 = new javax.swing.JLabel();
        main_317 = new javax.swing.JPanel();
        jPanel1_QuanLySinhVien_317 = new javax.swing.JPanel();
        jLabel2_qlsv_317 = new javax.swing.JLabel();
        icon_qlsv_317 = new javax.swing.JLabel();
        jPanel2_DangKiKTX_317 = new javax.swing.JPanel();
        jLabel2_dkktx_317 = new javax.swing.JLabel();
        icon_dkktx_317 = new javax.swing.JLabel();
        jPanel3_QuanLyPhongKTX_317 = new javax.swing.JPanel();
        jLabel2_qlpktx_317 = new javax.swing.JLabel();
        jLabel4_icon_qlpktx_317 = new javax.swing.JLabel();
        jPanel4_ThongKe_317 = new javax.swing.JPanel();
        jLabel2_tk_317 = new javax.swing.JLabel();
        jLabel8_icon_tk_317 = new javax.swing.JLabel();
        jPanel5_ThuPhi_317 = new javax.swing.JPanel();
        jLabel2_tp_317 = new javax.swing.JLabel();
        jLabel7_icon_tp_317 = new javax.swing.JLabel();
        jPanel1_QuanLyNhaXe_317 = new javax.swing.JPanel();
        jLabel1_qlnx_317 = new javax.swing.JLabel();
        jLabel6_icon_qlnx_317 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_317.setBackground(new java.awt.Color(255, 255, 255));
        bg_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar_317.setBackground(new java.awt.Color(54, 33, 89));
        sideBar_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CaiDat_317.setBackground(new java.awt.Color(64, 43, 100));
        CaiDat_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CaiDat_317MousePressed(evt);
            }
        });
        CaiDat_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_cd_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cd_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3592840-cog-gear-machine-office-radio-settings-setting-settings_107729.png"))); // NOI18N
        CaiDat_317.add(icon_cd_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 60, 38));

        bd_cd_317.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout bd_cd_317Layout = new javax.swing.GroupLayout(bd_cd_317);
        bd_cd_317.setLayout(bd_cd_317Layout);
        bd_cd_317Layout.setHorizontalGroup(
            bd_cd_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bd_cd_317Layout.setVerticalGroup(
            bd_cd_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        CaiDat_317.add(bd_cd_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Name_cd_317.setBackground(new java.awt.Color(255, 255, 255));
        Name_cd_317.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Name_cd_317.setForeground(new java.awt.Color(255, 255, 255));
        Name_cd_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_cd_317.setText("CÀI ĐẶT");
        CaiDat_317.add(Name_cd_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        sideBar_317.add(CaiDat_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 80));

        TrangChu_317.setBackground(new java.awt.Color(64, 43, 100));
        TrangChu_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrangChu_317MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrangChu_317MousePressed(evt);
            }
        });
        TrangChu_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_TC_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_TC_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/go_home_icon_181144.png"))); // NOI18N
        TrangChu_317.add(icon_TC_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 60, 38));

        bd_tc_317.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout bd_tc_317Layout = new javax.swing.GroupLayout(bd_tc_317);
        bd_tc_317.setLayout(bd_tc_317Layout);
        bd_tc_317Layout.setHorizontalGroup(
            bd_tc_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bd_tc_317Layout.setVerticalGroup(
            bd_tc_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        TrangChu_317.add(bd_tc_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 80));

        Name_TC_317.setBackground(new java.awt.Color(255, 255, 255));
        Name_TC_317.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Name_TC_317.setForeground(new java.awt.Color(255, 255, 255));
        Name_TC_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_TC_317.setText("TRANG CHỦ");
        TrangChu_317.add(Name_TC_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        sideBar_317.add(TrangChu_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 80));

        DangXuat_317.setBackground(new java.awt.Color(64, 43, 100));
        DangXuat_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuat_317MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuat_317MousePressed(evt);
            }
        });
        DangXuat_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_dx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_dx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/system_log_out_icon_181207.png"))); // NOI18N
        DangXuat_317.add(icon_dx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 60, 38));

        bd_dx_317.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout bd_dx_317Layout = new javax.swing.GroupLayout(bd_dx_317);
        bd_dx_317.setLayout(bd_dx_317Layout);
        bd_dx_317Layout.setHorizontalGroup(
            bd_dx_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bd_dx_317Layout.setVerticalGroup(
            bd_dx_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        DangXuat_317.add(bd_dx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Name_dx_317.setBackground(new java.awt.Color(255, 255, 255));
        Name_dx_317.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Name_dx_317.setForeground(new java.awt.Color(255, 255, 255));
        Name_dx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_dx_317.setText("ĐĂNG XUẤT");
        DangXuat_317.add(Name_dx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        sideBar_317.add(DangXuat_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 80));
        sideBar_317.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 260, 10));

        Name_KTX_317.setBackground(new java.awt.Color(255, 255, 255));
        Name_KTX_317.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Name_KTX_317.setForeground(new java.awt.Color(255, 255, 255));
        Name_KTX_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_KTX_317.setText("Quản Lý Ký Túc Xá");
        sideBar_317.add(Name_KTX_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 50));

        bg_317.add(sideBar_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 553));

        header_317.setBackground(new java.awt.Color(122, 72, 211));
        header_317.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_317MouseDragged(evt);
            }
        });
        header_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_317MousePressed(evt);
            }
        });

        close_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shutdown_30px.png"))); // NOI18N
        close_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_317MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout header_317Layout = new javax.swing.GroupLayout(header_317);
        header_317.setLayout(header_317Layout);
        header_317Layout.setHorizontalGroup(
            header_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_317Layout.createSequentialGroup()
                .addContainerGap(620, Short.MAX_VALUE)
                .addComponent(close_317, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_317Layout.setVerticalGroup(
            header_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg_317.add(header_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 660, 40));

        main_317.setBackground(new java.awt.Color(120, 100, 200));
        main_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1_QuanLySinhVien_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel1_QuanLySinhVien_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1_QuanLySinhVien_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_qlsv_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_qlsv_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_qlsv_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_qlsv_317.setText("QUẢN LÝ SINH VIÊN");
        jLabel2_qlsv_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1_QuanLySinhVien_317.add(jLabel2_qlsv_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        icon_qlsv_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_qlsv_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/management_64px.png"))); // NOI18N
        jPanel1_QuanLySinhVien_317.add(icon_qlsv_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel1_QuanLySinhVien_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, 170));

        jPanel2_DangKiKTX_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel2_DangKiKTX_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2_DangKiKTX_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_dkktx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_dkktx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_dkktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_dkktx_317.setText("ĐĂNG KÍ KTX");
        jLabel2_dkktx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2_DangKiKTX_317.add(jLabel2_dkktx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        icon_dkktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_dkktx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student_registration_64px.png"))); // NOI18N
        jPanel2_DangKiKTX_317.add(icon_dkktx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel2_DangKiKTX_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, 170));

        jPanel3_QuanLyPhongKTX_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel3_QuanLyPhongKTX_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3_QuanLyPhongKTX_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_qlpktx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_qlpktx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_qlpktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_qlpktx_317.setText("QUẢN LÝ PHÒNG KTX");
        jLabel2_qlpktx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3_QuanLyPhongKTX_317.add(jLabel2_qlpktx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        jLabel4_icon_qlpktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_icon_qlpktx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bunk_bed_64px.png"))); // NOI18N
        jPanel3_QuanLyPhongKTX_317.add(jLabel4_icon_qlpktx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel3_QuanLyPhongKTX_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 180, 170));

        jPanel4_ThongKe_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel4_ThongKe_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4_ThongKe_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_tk_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_tk_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_tk_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_tk_317.setText("THỐNG KÊ");
        jLabel2_tk_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4_ThongKe_317.add(jLabel2_tk_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        jLabel8_icon_tk_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8_icon_tk_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/statistics_64px.png"))); // NOI18N
        jPanel4_ThongKe_317.add(jLabel8_icon_tk_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel4_ThongKe_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 170));

        jPanel5_ThuPhi_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel5_ThuPhi_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5_ThuPhi_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_tp_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_tp_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_tp_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_tp_317.setText("THU PHÍ");
        jLabel2_tp_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5_ThuPhi_317.add(jLabel2_tp_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        jLabel7_icon_tp_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7_icon_tp_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/expensive_64px.png"))); // NOI18N
        jPanel5_ThuPhi_317.add(jLabel7_icon_tp_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel5_ThuPhi_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, 170));

        jPanel1_QuanLyNhaXe_317.setBackground(new java.awt.Color(121, 130, 222));
        jPanel1_QuanLyNhaXe_317.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1_QuanLyNhaXe_317.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_qlnx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1_qlnx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_qlnx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_qlnx_317.setText("QUẢN LÝ NHÀ XE");
        jLabel1_qlnx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1_QuanLyNhaXe_317.add(jLabel1_qlnx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 50));

        jLabel6_icon_qlnx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_icon_qlnx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/garage_64px.png"))); // NOI18N
        jPanel1_QuanLyNhaXe_317.add(jLabel6_icon_qlnx_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        main_317.add(jPanel1_QuanLyNhaXe_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 180, 170));

        bg_317.add(main_317, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 660, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_317, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            int xy_317,xx_317;
    private void header_317MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_317MouseDragged
             int x_317 = evt.getXOnScreen();
        int y_317 = evt.getYOnScreen();
        this.setLocation(x_317-xx_317,y_317-xy_317);        // TODO add your handling code here:
    }//GEN-LAST:event_header_317MouseDragged

    private void header_317MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_317MousePressed
        // TODO add your handling code here:
         xx_317 = evt.getX();
        xy_317 = evt.getY();
    }//GEN-LAST:event_header_317MousePressed

    private void close_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_317MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_317MouseClicked

    private void TrangChu_317MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChu_317MousePressed
        // TODO add your handling code here:
         setColor_317(TrangChu_317); 
        bd_tc_317.setOpaque(true);
        resetColor_317(new JPanel[]{CaiDat_317,DangXuat_317}, new JPanel[]{bd_cd_317, bd_dx_317});
        
    }//GEN-LAST:event_TrangChu_317MousePressed

    private void TrangChu_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChu_317MouseClicked
        // TODO add your handling code here
       
    }//GEN-LAST:event_TrangChu_317MouseClicked

    private void CaiDat_317MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaiDat_317MousePressed
        // TODO add your handling code here:
        setColor_317(CaiDat_317); 
        bd_cd_317.setOpaque(true);
       resetColor_317(new JPanel[]{TrangChu_317,DangXuat_317}, new JPanel[]{bd_tc_317, bd_dx_317});
    }//GEN-LAST:event_CaiDat_317MousePressed

    private void DangXuat_317MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_317MousePressed
        // TODO add your handling code here:
        setColor_317(DangXuat_317); 
        bd_dx_317.setOpaque(true);
        resetColor_317(new JPanel[]{TrangChu_317,CaiDat_317}, new JPanel[]{bd_tc_317,bd_cd_317});
    }//GEN-LAST:event_DangXuat_317MousePressed

    private void DangXuat_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_317MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DangXuat_317MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTXManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTXManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTXManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTXManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KTXManagement().setVisible(true);
            }
        });
    }
    
     private void setColor_317(JPanel pane_317)
    {
        pane_317.setBackground(new Color(85,65,118));
    }
    private void resetColor_317(JPanel [] pane_317, JPanel [] indicators_317)
    {
        for(int i=0;i<pane_317.length;i++){
           pane_317[i].setBackground(new Color(64,43,100));
           
        } for(int i=0;i<indicators_317.length;i++){
           indicators_317[i].setOpaque(false);           
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaiDat_317;
    private javax.swing.JPanel DangXuat_317;
    private javax.swing.JLabel Name_KTX_317;
    private javax.swing.JLabel Name_TC_317;
    private javax.swing.JLabel Name_cd_317;
    private javax.swing.JLabel Name_dx_317;
    private javax.swing.JPanel TrangChu_317;
    private javax.swing.JPanel bd_cd_317;
    private javax.swing.JPanel bd_dx_317;
    private javax.swing.JPanel bd_tc_317;
    private javax.swing.JPanel bg_317;
    private javax.swing.JLabel close_317;
    private javax.swing.JPanel header_317;
    private javax.swing.JLabel icon_TC_317;
    private javax.swing.JLabel icon_cd_317;
    private javax.swing.JLabel icon_dkktx_317;
    private javax.swing.JLabel icon_dx_317;
    private javax.swing.JLabel icon_qlsv_317;
    private javax.swing.JLabel jLabel1_qlnx_317;
    private javax.swing.JLabel jLabel2_dkktx_317;
    private javax.swing.JLabel jLabel2_qlpktx_317;
    private javax.swing.JLabel jLabel2_qlsv_317;
    private javax.swing.JLabel jLabel2_tk_317;
    private javax.swing.JLabel jLabel2_tp_317;
    private javax.swing.JLabel jLabel4_icon_qlpktx_317;
    private javax.swing.JLabel jLabel6_icon_qlnx_317;
    private javax.swing.JLabel jLabel7_icon_tp_317;
    private javax.swing.JLabel jLabel8_icon_tk_317;
    private javax.swing.JPanel jPanel1_QuanLyNhaXe_317;
    private javax.swing.JPanel jPanel1_QuanLySinhVien_317;
    private javax.swing.JPanel jPanel2_DangKiKTX_317;
    private javax.swing.JPanel jPanel3_QuanLyPhongKTX_317;
    private javax.swing.JPanel jPanel4_ThongKe_317;
    private javax.swing.JPanel jPanel5_ThuPhi_317;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel main_317;
    private javax.swing.JPanel sideBar_317;
    // End of variables declaration//GEN-END:variables
}
